name = "wedding-dashboard-api"
compatibility_date = "2026-01-01"

pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "wedding-db"
database_id = "d5da608f-9f23-4bd7-a500-29235a6e063a"

[[kv_namespaces]]
binding = "CACHE"
id = "e67630cff7ce4eb2ad401c3ffba70c7b"