name = "wedding-dashboard-api"
main = "src/index.js"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "wedding-db"
database_id = "78cd1cea-5376-4ce6-bb51-e56c678bf658"